main.go
Since promlogConfig was moved to the init() function, we need to re-assign the variable to a promlogConfig that was already declared earlier in the function.
=> Fixing a problem with flags

main.go
This PR is for aligning [Exporter logs with ADR-6](https://issues.redhat.com/projects/PLNSRVCE/issues/PLNSRVCE-1290).
Here's a sample output after switch to JSON endoer
```
➜  pipeline-service-exporter (main) go run main.go                                                                               ✭ ✱
{"level":"info","ts":1688390488.3012707,"logger":"main","msg":"Starting pipeline_service_exporter","version":"(version=, branch=, revision=unknown)"}
{"level":"info","ts":1688390488.301288,"logger":"main","msg":"Build context","build":"(go=go1.20.5, platform=linux/amd64, user=, date=)"}
{"level":"info","ts":1688390488.301291,"logger":"main","msg":"Starting Server: ","listen_address":":9117"}
{"level":"info","ts":1688390499.6877043,"logger":"controller","msg":"get of pipelinerun CRD …
```
=> switch to JSONencoder for logging

.tekton/pull-request.yaml, .tekton/push.yaml
Moving to OSP 1.11, got the bundle resolution broken. Using the new format also has performance benefit.
=> Update PaC bundle resolution

README.md, collector/collector.go, collector/collector_test.go, collector/controller.go, collector/metrics.go, collector/metrics_test.go, collector/pipelinerun.go, collector/taskrun.go, docs/metrics-specification.md, main.go
1) while @adambkaplan and I initially tried to minimize cardinality of the metrics, he and I had a conversation where we agreed that we needed to add a way to opt into greater cardinality; minimally during our performance testing; perhaps on by default long term;  added a commit which allows for adding the pipeline name as a label on the scheduled duration metric
2) added a task run level scheduled duration metric, with opt into a task name label, as an alternative to `tekton_pipelines_controller_taskruns_pod_latency_*` from upstream, where both @jhutar and I have seen odd results
3) added a new metric to highlight the gap in time between the scheduling of sequential  taskruns within a pipelinerun
=> PLNSRVCE-1407: performance workgroup motivated metrics

collector/collector.go, collector/collector_test.go, collector/pipelinerun.go
- pivot and default to on, but with minimal labeling (namespace)
- with additional labels, added better logic around retrieval of task/pipeline name instead of dynamically generated run names
=> PLNSRVCE-1407: second pass at taskrun gap metric

collector/collector.go, collector/collector_test.go, collector/pipelinerun.go, collector/pipelinerun_test.go, collector/rawyaml.go, docs/metrics-specification.md
initial testing in staging proved that with enough concurrency, the `Status.ChildReferences` array is minimally not sorted based on when the task runs were created, so we explicitly sort for that so we do not get negative values for the gap samples
for reference, the doc on specifying execution order:  https://tekton.dev/docs/pipelines/pipelines/#configuring-the-task-execution-order
This addresses parallel task runs at the start of a pipelinerun, different threads of taskrun dependency chains, and a final task run dependent on multiple threads/chains by
Also added 
- actual RHTAP staging runs which exhibited the negative number bug for validation
- unit tests for the controller runtime filters
- increased the validation of the actual metric data in the unit test to verify no negative …
=> PLNSRVCE-1431: Fix the presence with enough concurrenct of negative values for 'pipelinerun_duration_between_taskruns_milliseconds_sum'

collector/collector.go, collector/collector_test.go, collector/controller.go, collector/pipelinerun.go, collector/pipelinerun_test.go, docs/metrics-specification.md, go.mod
- implemented as a gauge, where deletion of failed pipelineruns is the "decrementing" action
- while a controller with caching client is created, and we increment in real time
- we also have a background controller runtime action which resets the metric, relists, and effectively handles deletes in that fashion
- real time processing of deletes for metrics too problematic given controller QofS around deletes
- unit tests and docs included
- geared towards alerting
=> PLNSRVCE-1405: provide a metric for pipelineruns marked failed by tekton because pvc quota prevented required pvc(s) to be created

collector/collector.go, collector/collector_test.go
The taskrun gap histogram metric still had the bucket specification that was copied and pasted from our existing histograms measured in seconds. Multipled by 1000 as needed to shift the buckets appropriately.
Also added a 'status' label with 'succeeded' and 'failed' values to correlate with a similar label available on the upstream pipelineruns duration metric, in case we see patterns where gaps vary based on failures in the underlying containers.
@ramessesii2 @Roming22 when we start talking about SLAs for underlying tekton, based on the performance WG experience, I believe we should exclude the time taken in underlying pods/containers (which pipelinerun duration includes for example), and focus on how quickly for example tekton processes things in between the containers.
For example, if …
=> PLNSRVCE-1443: make gap histogram buckets appropriate for milliseconds

collector/collector.go, collector/collector_test.go, collector/controller.go, collector/metrics.go, collector/metrics_test.go, collector/pipelinerun.go, collector/pipelinerun_test.go, collector/pod.go, collector/pod_test.go, collector/taskrun.go, collector/taskrun_test.go, docs/metrics-specification.md
So in working the wait count and wait times for task/pipeline resolution, I ended up seeing again the upstream pod latency metrics, which is an odd calculation of 
the last transition time of the `corev1.PodScheduled` condition minus the pod create time
So after a few passes at the tekton reconcile loops and k8s godoc around some of the pod status fields, I extrapolated this event sequencing:
```
Observed sequence from testing and tekton/k8s code examination:
- taskrun created by external user or pipelinerun reconciler, and k8s sets the taskrun create timestap
- on first reconcile event loop, taskrun ConditionSucceeded condition is intialized to pending and the startime is set
- "prepare" will see if resolutionrequest is needed, and if so, error is returned to controller fw and requeue …
```
=> PLNSRVCE-1406,PLNSRVCE-1407: Craft more metrics around measuring the gaps between creation of tekton objects and starting of pod/containers

collector/controller.go, collector/pipeline_reference_wait_time.go, collector/pipeline_reference_wait_time_test.go, collector/task_reference_wait_time.go, collector/task_reference_wait_time_test.go
So this PR adds the metrics for time spent waiting on bundle resolution for both any task or pipeline refs.
NOTE - this PR introduces a new file structure which hopefully simplifies by centralizing the bits needed for a given metric.
I envision in a separate PR restructuring the existing metrics to this new pattern.  Aside from centralizing related bits, it should better facilitate concurrent PRs from different folks in the future.
=> PLNSRVCE-1406:  add metrics for wait time on pipelne/task reference resolution

collector/controller.go, collector/pipeline_reference_wait_time.go, collector/pipeline_reference_wait_time_test.go, collector/pipelinerun_create_to_start_time.go, collector/pipelinerun_create_to_start_time_test.go, collector/pipelinerun_taskrun_complete_create_gaps.go, collector/pipelinerun_taskrun_complete_create_gaps_test.go, collector/rawyaml.go, collector/task_reference_wait_time.go, collector/task_reference_wait_time_test.go, collector/taskrun_create_to_start_time.go, collector/taskrun_create_to_start_time_test.go, collector/throttled_by_pvc_count.go, collector/throttled_by_pvc_count_test.go, collector/utils.go, collector/utils_test.go
fyi left some usage of v1beta1 in the unit tests (rawyaml.go), where I mimic the v1beta1 to v1 conversion done in the upstream tekton conversion webhook 
there is a tl;dr level analysis in https://issues.redhat.com/browse/RHTAP-1048?focusedId=23158263&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23158263 around how we can just watch for v1 type objects and still get v1beta1 type objects
=> PLNSRVCE-1440: switch watches / default mode from v1beta1 to v1

collector/controller.go, collector/throttled_by_pvc_count.go
For whatever reason, in the 4 RHTAP clusters, the multi-tenant prod cluster sees some periodic instances of the metrics-exporter having to restart. After a few instances, we finally got some useful information in the previous logs.  As it turns out, even after the CRDs are available, if we hit things too soon as Tekton is still coming up, the controller-runtime's attempts to establish watches either get 500s or time out, causing controller-runtime to exit, and our metrics-exporter pod restarting.  This change adds a List operation after the get CRD operation in our retry loop to help discern that apiserver plus Tekton is really ready to receiving watch/list requests.
@openshift-pipelines/pipelines-service FYI 
Error logs that can occur:
``` …
```
=> PLNSRVCE-1497: additional protection to not start controller-runtime watches too soon

collector/pipelinerun_create_to_start_time.go, collector/pipelinerun_create_to_start_time_test.go, collector/taskrun_create_to_start_time.go, collector/taskrun_create_to_start_time_test.go
While tracking our scheduling alert appstudio grafana panel in RHTAP prod, saw some evidence that failed runs overtly affected the ration calculation, so adding the ability to filter out failed runs.
=> add status label to pipelinerun/taskrun schedule metrics

collector/controller.go, collector/overhead_alert_metrics.go, collector/overhead_alert_metrics_test.go, collector/pipelinerun_create_to_start_time.go, collector/pipelinerun_taskrun_complete_create_gaps.go, collector/taskrun_create_to_start_time.go, collector/taskrun_create_to_start_time_test.go, collector/utils.go
We seen periods with our overhead grafana panels where user defined pipelineruns with very short durations, but even the smallest bit of overhead (where some subsecond overhead could have rounded up to even 1 second), contaminated our overhead percentages.  Especially for the execution overhead query.
This commit does two things
- aggregates the multiple historgrams used to calculate metrics into one histogram; this will help with performance from the dashboard, especially on the app-sre dashboard, based on what I saw with executing our current queries there
- adds filter step as part of calcuating the new metric to not include these pipelineruns that are relatively much shorter than the RHTAP defined pipelines in build-definitions.
This work also includes some code reorganization so that …
=> PLNSRVCE-1418,PLNSRVCE-1419: create an aggregated metric with filtering for our overhead alerts

collector/controller.go, collector/overhead_alert_metrics.go, collector/overhead_alert_metrics_test.go, collector/pipelinerun_taskrun_complete_create_gaps_test.go, collector/utils.go
The changes from https://github.com/openshift-pipelines/pipeline-service-exporter/pull/52 did not in fact properly tag and then filter pipelineruns who experience throttling of their taskruns.  Most notably was the controller runtime filter excluded pipelineruns from the reconcilation there were not completed.  Also, the labeling was only occuring within the block that confirmed the pipelinerun completed.  The condition in fact wil only occur while things are running.
@openshift-pipelines/pipelines-service PTAL
=> PLNSRVCE-1585: fix filtering of throttled pipelineruns form execution overhead metric 

collector/overhead_alert_metrics.go, collector/overhead_alert_metrics_test.go, collector/utils.go
We finally had a throttling event in staging and still did not see the exporter filter and tag; so this time contrived some throttling events in a test cluster sorted out some edge case issues with the code around timings between taskrun updates and pipelinerun updates.
rh-pre-commit.version: 2.1.0
=> PLNSRVCE-1585: more filter on throttle fixes

collector/throttled_by_pvc_count.go
although it can be slow acting over many, many days, and plenty of GC is occurring in the exporter, the use of dynamically created namespace in our e2e's leads to slow growth in the pvc ns cache map, and I've seen exporter have to recycle because of hitting the mem limit about once a month; the effect is that stats for these ephemeral namespaces, or for tenants with long bouts of inactivity, will show up as 'no data', which for our purposes only needing this stat when there are live pvc quota issues calling in pipeline svc for support, is OK
@openshift-pipelines/pipelines-service FYI
rh-pre-commit.version: 2.2.0
=> clear out pvc namespace cache on reset

README.md, collector/controller.go, collector/overhead_alert_metrics.go, collector/overhead_alert_metrics_test.go, collector/pipeline_reference_wait_time.go, collector/pipelinerun_create_to_start_time.go, collector/pipelinerun_taskrun_complete_create_gaps.go, collector/pipelinerun_taskrun_complete_create_gaps_test.go, collector/pod_create_to_complete_time.go, collector/pod_create_to_kubelet_ack_time.go, collector/pod_kubelet_ack_to_container_start_time.go, collector/task_reference_wait_time.go, collector/taskrun_create_to_start_time.go, collector/throttled_by_pvc_count.go, collector/throttled_by_pvc_count_test.go, collector/utils_test.go, docs/metrics-specification.md, main.go
As part of getting ready to add the 'no pod create attempts occuring for pipelineruns' metric for satisfying AppSRE/Infra feedback on core tekton health, I've been monitoring the memory usage on prod-r01 and the previous "simpler" approach of creating controllers per replicas may be now proving untenable. As konflux onboading increases, exporter's memory usage continues to grow, and I've had to increase the memory limit from 1G to 3G just in the last few weeks.
Note, the consolidating metrics into common reconcilers made the PVC gauge metric utilizing a reconciler in addition to the existing poller (a la what upstream does) untenable.  Hence we now just leverage the polling thread for the PVC metric.
rh-pre-commit.version: 2.2.0
@enarha @jkhelil PTAL …
=> PLNSRVCE-1692: consolidate metrics into single pipelinerun, taskrun, pod controllers tuned for performance; convert pvc metric to poll only

collector/controller.go, collector/pipeline_reference_wait_time.go, collector/pipeline_reference_wait_time_test.go, collector/pipelinerun_create_to_start_time.go, collector/pipelinerun_create_to_start_time_test.go, collector/pipelinerun_taskrun_complete_create_gaps.go, collector/pod_create_to_complete_time.go, collector/pod_create_to_complete_time_test.go, collector/pod_create_to_kubelet_ack_time.go, collector/pod_create_to_kubelet_ack_time_test.go, collector/pod_kubelet_ack_to_container_start_time.go, collector/pod_kubelet_ack_to_container_start_time_test.go, collector/task_reference_wait_time.go, collector/task_reference_wait_time_test.go, collector/taskrun_create_to_start_time.go, collector/taskrun_create_to_start_time_test.go, collector/utils.go, docs/metrics-specification.md
there proved to be too many edge cases where pipeline or task name would actually be the dynamically generated pipelinerun name or taskrun name, which adversely affected metric cardinality.
prometheus scraping on prod-rh01 started to timeout becase there were too many entries to return
restarting the instance alleviated things for now, but we need to avoid this moving forward.
rh-pre-commit.version: 2.2.0
=> remove task/pipeline labels as they can correspod to run names

collector/utils.go, collector/waiting_on_pipelinerun_kickoff.go, collector/waiting_on_pipelinerun_kickoff_test.go, collector/waiting_on_pod_create_attempt.go, collector/waiting_on_pod_create_attempt_test.go
after more monitoring of konflux prod over the last few weeks occasional bumps in the deadock metric per prometheus monitoring have conincided with k8s throttling
adding check like with the other alert metrics
our alerts will also includesum(pv_collector_bound_pvc_count{exported_namespace=~".+-tenant"}) == 0  to confirm that any pods that were started before a deadlock have completed
rh-pre-commit.version: 2.3.0
=> SRVKP-4523: add throttled check to deadlock checks

collector/controller.go, collector/waiting_on_resolutionrequest.go, collector/waiting_on_resolutionrequest_test.go, docs/metrics-specification.md
New resolver deadlock metric given recent hangs/crashloops
Note - since there is not metrics initialization/use in the remote resolver currently, starting downstream given konflux need, and to vet the metrics before potential upstreaming.
@enarha @savitaashture @khrm @divyansh42 FYI / PTAL minimally for education purposes
Successfully tested locally:
rh-pre-commit.version: 2.3.0
=> SRVKP-4532: add pending resolution request metrid
